### ISSUE TITLE
Add MIDI File not working

### ISSUE THREAD

**Issue by Biohazrx** [RandomThingsIveDone/Rafiano#2] opened 2024-10-19 04:40 UTC
after choosing the version of the notesheet Rafiano closes, and nothing happens did i do something wrong??

**Comment by RandomThingsIveDone** [comment] 2024-10-20 19:29
Could you send me The Midi file you are trying to convert ?

**Comment by RandomThingsIveDone** [comment] 2024-10-20 19:30
Could you please send me the MIDI file? It would be best if you could provide a link to the file you are trying to convert so I can attempt to reproduce your issue.

**Comment by Biohazrx** [comment] 2024-10-20 20:09
https://musescore.com/user/1515281/scores/1798726
i think this the one

**Comment by RandomThingsIveDone** [comment] 2024-10-20 21:17
Could you provide me with the file directly so I don't have to pay anything? If that's not possible, you can try to locate the Rafiano.exe in the File Explorer. Then, click on the path of the folder and type 'CMD.' This will open a Command Prompt window. In that window, type 'Rafiano.exe' to start the program. After that, try to convert the MIDI file. The program should close when an error occurs, but it should also display an error message, which you should send to me.

**Comment by Biohazrx** [comment] 2024-10-20 22:03
sorry this the file and you don't have to pay u can use this (https://chromewebstore.google.com/detail/music-score-downloader/jhogldboghgffknljgnomjkcfbapogdf) 
[Interstellar.zip](https://github.com/user-attachments/files/17452182/Interstellar.zip)

**Comment by Biohazrx** [comment] 2024-10-20 22:06
![image](https://github.com/user-attachments/assets/edc01eda-73b1-4a3b-8ba7-d327e2698c67)

im i using this wrong?

**Comment by RandomThingsIveDone** [comment] 2024-10-20 22:30
Okay, the problem is that the program doesn't work with ''\\" it only understands '/' in paths. I uploaded a hotfix that should resolve this issue. Please try it and let me know if this was the problem.

**Comment by Biohazrx** [comment] 2024-10-21 02:34
It's working now thanks, it's a great tool thanks for your work and effort
btw is there a key to pause or stop it?

**Comment by RandomThingsIveDone** [comment] 2024-10-21 16:38
I’ve added a new hotfix. You can now stop a song by pressing 'P' while the Rafiano window is focused. Unfortunately, I wasn’t able to find a good way to implement a stop or pause function that works when the window is not focused.

**Comment by Biohazrx** [comment] 2024-10-22 02:20
It's hard to focus on Rafiano but working like a charm for an emergency stop.

**Comment by RandomThingsIveDone** [comment] 2024-10-22 14:31
Okay, I'm going to close this issue for now. If you have more ideas or issues to help improve Rafiano, please feel free to open a new one.

**Closed as completed by RandomThingsIveDone** 2024-10-22 14:31 UTC
