### ISSUE TITLE
Notes not playing on Raft piano despite key presses being detected

### ISSUE THREAD

**Issue by Tokyma** [RandomThingsIveDone/Rafiano#5] opened 2024-11-25 19:23 UTC
Hello,

Thank you for creating Rafiano! I installed the tool and set it up as per the instructions. The key presses are being registered correctly (I tested this in a text editor, and all the keys are pressed as expected). However, when I use it with the piano in Raft, no notes are played in the game. My keyboard layout is in AZERTY, but i tried in QWERTY, it does not change anything.
### **Steps to Reproduce:**
Launch Raft.
Run the Rafiano executable.
Select a song
Focus the game window while on the piano.
Observe that no notes are played, even though key presses are working (tested in a text editor).
### **Expected Behavior:**
The notes should play on the Raft piano when the corresponding keys are pressed.

### **Actual Behavior:**
No notes are played on the Raft piano.

### **Additional Information:**
Operating System: [Windows 10]
Rafiano Version: v2.1.0
Keyboard Type: [AZERTY, QWERTY]
### **Other Tests:**
I verified that the keys are being pressed correctly by observing the input in a text editor.
I also tried a keybind test and it seems the 0-9 keys are not recognized correctly.
Playing the piano manually in Raft works as expected.
### **Possible Causes (speculation):**
Could Raft be blocking synthetic key inputs from tools like Rafiano?
Is there a specific game / windows setting to make it work?
Let me know if there’s anything I can provide (logs, additional tests, etc.) to help troubleshoot this issue.

Thank you for your help!

**Comment by RandomThingsIveDone** [comment] 2024-11-25 20:46
Unfortunately, I’m unable to reproduce this issue on my end. Could you confirm if the hotbar are set to the numbers 1–0? I tested your keyboard layout, and everything still works correctly on my setup.

If possible, could you record your screen while demonstrating the issue and include your game settings? Additionally, are there any programs running in the background that might intercept input while you’re playing Raft? Lastly, could there be any USB devices connected that might interfere with the input?

**Comment by Tokyma** [comment] 2024-11-25 22:47
Here is the recording of the problem : [https://www.youtube.com/watch?v=Rvwn1Prdks4], i can pick a song, i put the focus on the game and nothing happens, even if it seems to work in the text editor. I tried to close every program that was not needed, same for usb devices, just left my keyboard and mouse. I recorded in windowed mode for practical reason, but it does the same in fullscreen / exclusive mode.

**Comment by STALKER666YT** [comment] 2024-11-26 15:05
I tried the window mode and i dont have same problem

**Comment by STALKER666YT** [comment] 2024-11-26 16:53
Try to start Rafiano with administrator rights

**Comment by Tokyma** [comment] 2024-11-26 17:05
Hey, just to let you know i found a fix, at least that's working for me. As i thought, keys were being pressed but the method used in the script seemed to be ignored by the game. I got your python version (the same problem happened of course) and modified the NotesheetPlayer class with pyautogui instead of pynput. Now the game gets the inputs perfectly, but i think it may have broken the timings of the songs, notes seem to be played without rythm.

```python
class NotesheetPlayer:
    """
    Class for playing notesheets based on different player versions.
    """

    def __init__(self):
        pass

    @staticmethod
    def _player_v1(stdscr, song_notes: List[Dict]) -> bool:
        """
        Plays the notes of a given song by simulating key presses based on relative timings.

        Args:
            song_notes (List[Dict]): A list of dictionaries containing information about the song to be played.

        Returns:
            bool: True, if the song was played successfully.
        """
        stdscr.nodelay(True)

        for note_dic in song_notes:
            # Check for user input
            key = stdscr.getch()
            if key == ord('p') or key == ord('P'):  # Check for 'P' key press
                print("Playback stopped.")
                stdscr.nodelay(False)
                return False

            # Handle modifier (shift, space, etc.)
            modifier = note_dic["modifier"]
            if modifier == "shift":
                pyautogui.keyDown("shift")
            elif modifier == "space":
                pyautogui.keyDown("space")

            # Press the main note(s)
            for note in note_dic["notes"]:
                pyautogui.keyDown(note)  # Press the note key
            time.sleep(note_dic["press_time"])

            # Release the main note(s)
            for note in note_dic["notes"]:
                pyautogui.keyUp(note)

            # Release the modifier
            if modifier == "shift":
                pyautogui.keyUp("shift")
            elif modifier == "space":
                pyautogui.keyUp("space")

            time.sleep(note_dic["release_time"])

        stdscr.nodelay(False)
        return True

    @staticmethod
    def _player_v2(stdscr, song_notes: List[Dict]) -> bool:
        """
        Plays the notes of a given song by simulating key presses based on absolute timings.

        Args:
            song_notes (List[Dict]): A list of dictionaries containing information about the song to be played.

        Returns:
            bool: True, if the song was played successfully.
        """
        stdscr.nodelay(True)
        _PressRelease = {"shift": False, "space": False, "1": False, "2": False, "3": False,
                         "4": False, "5": False, "6": False, "7": False, "8": False, "9": False, "0": False}

        songNotes = NotesheetUtils.notesheet_easy_convert(song_notes)

        start_time = time.time()
        for notes in songNotes:
            # Check for user input
            key = stdscr.getch()
            if key == ord('p') or key == ord('P'):  # Check for 'P' key press
                print("Playback stopped.")
                stdscr.nodelay(False)
                return False

            while time.time() - start_time < notes[0]:
                time.sleep(0.001)

            # Handle the note presses and releases
            for note in notes[1:]:
                if _PressRelease[note]:
                    pyautogui.keyUp(note)
                    _PressRelease[note] = False
                else:
                    pyautogui.keyDown(note)
                    _PressRelease[note] = True

        stdscr.nodelay(False)
        return True

    def play(self, stdscr, song_notes: List[Dict], version: str) -> bool:
        """
        Plays the notes of a given song by simulating key presses.

        Args:
            song_notes (List[Dict]): A list of dictionaries containing information about the song to be played.
            version (str): The version of the player to use ("1.0" for relative timing, "2.0" for absolute timing).

        Returns:
            bool: True, if the song was played successfully.
        """
        if version == "1.0":
            return self._player_v1(stdscr, song_notes)
        elif version == "2.0":
            return self._player_v2(stdscr, song_notes)
        else:
            raise ValueError("Unsupported version")```

**Comment by RandomThingsIveDone** [comment] 2024-11-26 19:13
Could you try this version: [Rafiano.zip](https://github.com/user-attachments/files/17924717/Rafiano.zip)? You will need to install the keyboard library using the following command: pip install keyboard.

**Comment by STALKER666YT** [comment] 2024-11-26 19:52
[Rafiano.zip](https://github.com/user-attachments/files/17925160/Rafiano.zip)
Rafiano with script by Tokyoma

**Comment by STALKER666YT** [comment] 2024-11-26 20:21
> Could you try this version: [Rafiano.zip](https://github.com/user-attachments/files/17924717/Rafiano.zip)? You will need to install the keyboard library using the following command: pip install keyboard.

[Rafiano.zip](https://github.com/user-attachments/files/17925378/Rafiano.zip)
exe of script with notesheets and config file

**Comment by STALKER666YT** [comment] 2024-11-26 20:24
i cant try it now because my raft keep crashing, please try it

**Comment by STALKER666YT** [comment] 2024-11-26 21:46
Works fine

**Comment by Tokyma** [comment] 2024-11-26 21:50
For me this version does not work, no notes are played in game and it does not seem to write any number in my text editor either.

**Comment by STALKER666YT** [comment] 2024-11-26 21:52
> For me this version does not work, no notes are played in game and it does not seem to write any number in my text editor either.

What version do you use?
Try my zip with full Rafiano

**Comment by Tokyma** [comment] 2024-11-26 21:52
I tried both, with the python script and your executable

**Comment by STALKER666YT** [comment] 2024-11-26 21:53
> I tried both, with the python script and your executable

What your version of python?

**Comment by Tokyma** [comment] 2024-11-26 21:54
> > I tried both, with the python script and your executable
> 
> What your version of python?

3.10.11

**Comment by STALKER666YT** [comment] 2024-11-26 21:55
My version is 3.12 and all work really fine (Latest 3.13 but not all scripts work with 3.13)

**Comment by STALKER666YT** [comment] 2024-11-26 21:55
Try update i think

**Comment by Tokyma** [comment] 2024-11-27 17:07
I tried with python 3.12.7, but nothing changed.

**Comment by STALKER666YT** [comment] 2024-11-27 17:25
This problem can be caused by Directx 
I think only solution is your script

**Comment by Tokyma** [comment] 2024-11-27 17:29
Yeah, i'll try to figure this out when i have time, i just have to fix the rythm and it should be good. I'll keep you informed, thanks for your time.

**Comment by STALKER666YT** [comment] 2024-11-27 17:30
Good luck! There's a lot of work there

**Comment by RandomThingsIveDone** [comment] 2024-11-27 22:44
[Rafiano.zip](https://github.com/user-attachments/files/17940723/Rafiano.zip) Could you try this version instead? It uses a more barebones version of pyautogui for the keyboard functionality. The executable would otherwise be way too large—33MB!!! instead of just 7MB. Please make sure that in the settings, the API is set to pyautogui.

**Comment by Tokyma** [comment] 2024-12-01 17:18
Hey, i tried your version, it is working as well as the script i modified on my side, notes are recognized and played correctly only with the Pyatutogui API, thanks ! The only problem left that i discovered is that you have to specify which shift you are using as a modifier, or Raft won't recognize the keypress. With yout script, i just had to specify shiftright (as i pasted) and it's working perfectly :D Thanks a lot for all the modifications and the new script. I hope it will help the few people like me that had the same issue.
```python
            elif read_notesheet:
                split_notes = notesheet_line.split(" ")
                if split_notes[1].upper() == "":
                    modifier_key = "up"
                elif split_notes[1].upper() == "SH":
                    modifier_key = "shiftright"
                elif split_notes[1].upper() == "SP":
                    modifier_key = "space"
                else:
                    raise Exception("Invalid modifier value")
```

**Comment by RandomThingsIveDone** [comment] 2024-12-02 22:45
I’ll close this issue for now. I’ve released a new version with all the changes applied, and Rafiano should now work as expected. If something still doesn’t work, feel free to reopen the issue.

**Closed as completed by RandomThingsIveDone** 2024-12-02 22:45 UTC
Labels: good first issue
